### ISSUE TITLE
建议在print()方法执行前，增加$nextTick钩子

### ISSUE THREAD

**Issue by yinjunonly** [pcloth/vue-easy-print#2]
如果在界面一加载就打印，可能出现slot里面的html还未渲染完毕，直接打印可能出现样式丢失的问题。

**Comment by yinjunonly** [comment]
`    setTimeout(() => {
                $iframe.contentWindow.print();
            }, 100);
`
可改为
`this.$nextTick(() => {
      setTimeout(() => {
                $iframe.contentWindow.print();
            }, 100);
}）`
更为保险

**Comment by pcloth** [comment]
可以有，感谢。
