### ISSUE TITLE
如何去掉页眉页脚

### ISSUE THREAD

**Issue by Little-Little-Monster** [pcloth/vue-easy-print#6]
请问怎么去掉页眉页脚呢？我这边在组件中写了去掉页眉的样式，但是并没有加载进去
`<style media="print" scoped>
    @page{
        size: auto;
        margin: 0mm;
    }
</style>`

**Comment by JoneYing** [comment]
请问你这个问题解决了吗?

**Comment by pcloth** [comment]
禁止的代码写到模板里面，可以禁止页眉
